# Generated by Django 4.0.6 on 2022-11-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_cart_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
